version: 2
jobs:
  # Define a "check_links" job to be run with Circle
  check_links:
    # This is the base environment that Circle will use
    docker:
      - image: sushma4y/ubuntu:latest 
      
    steps:
      - run:
          name: Output the Version
          command: |
            lsb_release -a
    

