version: 2
jobs:
  # Define a "check_links" job to be run with Circle
  check_links:
    # This is the base environment that Circle will use
    docker:
      - image: circleci/python:3.6-stretch
      
    steps:
      - run:
          name: Output the Version
          command: cat /etc/issue
           
           
      - run: sudo apt-get update
      - run: sudo apt-get install linkchecker
      - run: linkchecker --version
      - run: linkchecker --check-extern _build/html
            
            
workflows:
  version: 2
  default:
    jobs:
      - check_links
    

